# Generated by Django 3.2.6 on 2021-08-09 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokenauth', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='EmployeeT',
        ),
    ]
