# Generated by Django 3.2.6 on 2021-08-09 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokenauth', '0002_rename_employee_employeet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeT',
            new_name='Employee',
        ),
    ]
